"""empty message

Revision ID: 3f53f92c629d
Revises: bdd843684d42
Create Date: 2024-01-31 07:40:52.992188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f53f92c629d'
down_revision = 'bdd843684d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('letter', sa.String(length=3), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_brand',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('category_id', 'brand_id')
    )
    op.create_table('category_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('goods_num', sa.Integer(), nullable=True),
    sa.Column('is_show', sa.Boolean(), nullable=True),
    sa.Column('is_menu', sa.Boolean(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category_goods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_goods_parent_id'), ['parent_id'], unique=False)

    op.create_table('para',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('options', sa.String(length=2000), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pref',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('buy_money', sa.Integer(), nullable=True),
    sa.Column('pre_money', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('state', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sku',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sn', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('alert_num', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('images', sa.String(length=2000), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.Time(), nullable=True),
    sa.Column('update_time', sa.Time(), nullable=True),
    sa.Column('spu_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=200), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('spec', sa.String(length=200), nullable=True),
    sa.Column('sale_num', sa.Integer(), nullable=True),
    sa.Column('comment_num', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sku', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sku_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sku_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sku_update_time'), ['update_time'], unique=False)

    op.create_table('spec',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('options', sa.String(length=2000), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spu',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sn', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('caption', sa.String(length=100), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('category1_id', sa.Integer(), nullable=True),
    sa.Column('category2_id', sa.Integer(), nullable=True),
    sa.Column('category3_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('freight_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('images', sa.String(length=1000), nullable=True),
    sa.Column('sale_service', sa.String(length=50), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('spec_items', sa.String(length=3000), nullable=True),
    sa.Column('para_items', sa.String(length=3000), nullable=True),
    sa.Column('sale_num', sa.Integer(), nullable=True),
    sa.Column('comment_num', sa.Integer(), nullable=True),
    sa.Column('is_marketable', sa.SmallInteger(), nullable=True),
    sa.Column('is_enable_spec', sa.SmallInteger(), nullable=True),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('spec_num', sa.SmallInteger(), nullable=True),
    sa.Column('para_num', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template')
    op.drop_table('spu')
    op.drop_table('spec')
    with op.batch_alter_table('sku', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sku_update_time'))
        batch_op.drop_index(batch_op.f('ix_sku_status'))
        batch_op.drop_index(batch_op.f('ix_sku_category_id'))

    op.drop_table('sku')
    op.drop_table('pref')
    op.drop_table('para')
    with op.batch_alter_table('category_goods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_goods_parent_id'))

    op.drop_table('category_goods')
    op.drop_table('category_brand')
    op.drop_table('brand')
    # ### end Alembic commands ###
