"""empty message

Revision ID: bdd843684d42
Revises: 
Create Date: 2024-01-31 05:30:27.428614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd843684d42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=25), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('tag', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('captcha', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_captcha_created_time'), ['created_time'], unique=False)

    op.create_table('content_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('tag', sa.String(length=30), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_category_created_time'), ['created_time'], unique=False)

    op.create_table('sms_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('captcha', sa.String(length=6), nullable=False),
    sa.Column('tag', sa.Boolean(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_captcha', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_captcha_created_time'), ['created_time'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('pwd', sa.String(length=250), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_time'), ['created_time'], unique=False)

    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('sequence', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['content_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_created_time'), ['created_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_created_time'))

    op.drop_table('content')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_created_time'))

    op.drop_table('user')
    with op.batch_alter_table('sms_captcha', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_captcha_created_time'))

    op.drop_table('sms_captcha')
    with op.batch_alter_table('content_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_category_created_time'))

    op.drop_table('content_category')
    with op.batch_alter_table('captcha', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_captcha_created_time'))

    op.drop_table('captcha')
    # ### end Alembic commands ###
